#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, use it in
#       instead.
#
#   (2) Avoid modifying this script unless you know what you are doing -- it
#       looks complicated, but it is just a normal bash script whose purpose is
#       to make the start of Gradle easier to understand for beginners.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while [[ -h "$PRG" ]]; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(cd "$(dirname "$PRG")" && pwd -P)/"$(basename "$link")"
    fi
done
APP_HOME=$(cd "$(dirname "$PRG")" && pwd -P)
APP_NAME="Gradle"
APP_PID=$$

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
CYGWIN*)
    cygwin=true
    ;;
Darwin*)
    darwin=true
    ;;
MSYS* | MINGW*)
    msys=true
    ;;
NONSTOP*)
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
    javaexe="$JAVA_HOME/bin/java"
else
    javaexe="$(which java)"
fi

if [[ -z "$javaexe" ]] || ! [[ -x "$javaexe" ]]; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

if [[ -z "$JAVA_HOME" ]]; then
    warn "WARNING: JAVA_HOME environment variable is not set."
fi

# traverses directory structure from process work directory to filesystem root
# trying to find a settings.gradle or settings.gradle.kts in order to determine
# the Gradle user home.
# can be overridden by using the -Dorg.gradle.appname=myapp script parameter.
need_findBaseDir=true
if [[ "${GRADLE_SUPPRESS_DEPRECATION_WARNINGS}" != true ]]; then
    # Use the maximum available, or set MAX_FD != -1 to use that value.
    if ! eval "\$javaexe" \
        -Dorg.gradle.appname="\$APP_NAME" \
        -Dorg.gradle.appname=gradlew \
        -Dorg.gradle.wrapper.properties="\$APP_HOME/gradle/wrapper/gradle-wrapper.properties" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"; then
        exit $?
    fi
else
    if ! eval "\$javaexe" \
        -Dorg.gradle.appname="\$APP_NAME" \
        -Dorg.gradle.appname=gradlew \
        -Dorg.gradle.wrapper.properties="\$APP_HOME/gradle/wrapper/gradle-wrapper.properties" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"; then
        exit $?
    fi
fi
